### ISSUE TITLE
[Bug]: grouping step creates overlapping groups

### ISSUE THREAD

**Issue by fpavogt** [MeteoSwiss/ampycloud#107]
### Is there already an issue for this?

- [X] I found no existing issue for this bug.

### Describe the bug

The grouping step currently sets no restrictions on the vertical separation between the groups. In certain circumstances, groups can be found to have the exact same altitude, as for example in Geneva on 2018-04-30 @ 18:17 UTC (see example below). 

This behavior is a direct and unwanted behavior of the current grouping algorithm. Each sub-group identified is assigned to the slice where most of its points belong. In the example below, the majority of the points are found to be linked (according to the single linkage criterion) and assigned to the pink slice where the majority of them belong. A handful of isolated blue points are then all put inside one group assigned to the blue slice. Very clearly, however, the two groups are overlapping with each other.  

**Solution (?):**

A good option could be to verify that the groups identified are separated by some minimal distance (possibly a function of altitude) as is done for the layering step. The layering "validation" approach (see l.252-265 in layer.py) could be used for the grouping step - either by duplicating it in the grouping routine, or by extracting it to a higher level. Alternatively (and perhaps better, since it would not require any new parameter), **one could simply request that groups cannot be overlapping in terms of their vertical extent** - and if they are, to merge them.

There is the idea of a final verification step that all cloud layers are sufficiently offset from one another (see #88), which would help mask this bug. I suspect however that it would be best to fix the grouping step itself, rather than mask its deficiency with a subsequent correction. **The idea that groups cannot overlap one another would be easy to implement and quite meaningful - I would probably try this first ?**

### Screenshot

![20180430181700](https://github.com/MeteoSwiss/ampycloud/assets/13974615/6679a4ad-0d5c-4886-9dba-6c83f7ab9914)

### Steps to reproduce

Run the normal algorithm for the case above.

### Relevant log output

```shell
n.a.
```

### Environment

```markdown
ampycloud: v0.6.0.dev0
```

### Code of Conduct

- [X] I agree to follow the ampycloud Code of Conduct.

**Comment by fpavogt** [comment]
The idea of merging groups that are overlapping in altitude is dangerous, and could have unintended side effects. Here is an example where merging groups that overlap in terms of altitude would lead to the wrong result (merging of the two layers into one).

![ampycloud_demo](https://github.com/MeteoSwiss/ampycloud/assets/13974615/a3e46245-dfc8-4b8b-922e-472c7aa36bfa)

The corresponding (artificial) ceilometer hits are here, in case we want to add them to the list of tests:

[debug_107.csv](https://github.com/MeteoSwiss/ampycloud/files/13249380/debug_107.csv)

The criteria for merging groups is that they **should be overlapping both in altitude AND time**. This could perhaps be achieved using the LOWESS fit and fluffiness measure. For example, for each group, if LOWESS_1 + fluffiness_1 > LOWESS_2 - fluffiness_2 at any time step, then the groups should be merged. Else, we keep them separate.

**Comment by fpavogt** [comment]
@regDaniel @loforest: here some more thoughts on a possible implementation of an "alt-time no-overlap condition for groups":

1) At the end of the grouping step (for any given set of overlapping slices), select the largest group (in terms of points).
2) Optional: compute the min/max in alt and time. Check if these overlap with other groups. If not, move to the next largest group and start at 1) again.
3) Compute the convex hull of the group using [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html)
4) For all other groups, check if there hits land inside the hull. [This page](https://stackoverflow.com/questions/16750618/whats-an-efficient-way-to-find-if-a-point-lies-in-the-convex-hull-of-a-point-cl) contain several interesting options that should be tested, including several that only rely on scipy.
5) As soon as a point is found inside the hull, merge the two groups, and check the next smallest group. If no overlap is found, flag this group as "isolated" and start at 1) using the next largest group remaining.


This solution will fix the problem while still returning the correct result for the special case of two parallel layers above. The hope is that it will not be too computationally expansive.

**Comment by regDaniel** [comment]
Ciao @fpavogt I've identified 7 cases where we report clouds at the same altitude, I'll have a proper look at those cases and then decide if I go for a minimum separation or a no overlap approach.

**Comment by regDaniel** [comment]
It's actually quite tricky to cover all configurations that could "get you". At first glance, I liked the convex hull approach. But I found a case where I think it would fail (see plot below). Admittedly, it's an extreme example and it only happens because of the drastic rounding above the MSA. But I'm unsure if it couldn't happen at lower altitudes if the outlier points were correspondingly closer.
![image](https://github.com/MeteoSwiss/ampycloud/assets/26576213/2b4e3e0c-4e33-485d-83d7-8fe94e739a0f)

**Comment by fpavogt** [comment]
Very interesting example. Might be worth running it manually, removing 10'000 ft from each hit just to be certain. But the slicing would work the same. So would the grouping as far as I can tell. And this would definitely not be fixed by the Convex Hull approach.

A case like this can only be fixed with final sanity check after all the layers are identified. I'll try to put together a mock example to illustrate this case, to be used as an additional test.

**Comment by fpavogt** [comment]
This plan makes sense. But after seeing your example (and the mock demo below), I'm not sure that there's any point in implementing the Convex/Fluffy Hull solution, since it cannot handle all situations. It would be a lot of extra code for little gain (even though it would still make sense and solve some of the issue, of course). 

Instead of a final "compliance", what about doing it at the grouping step ? There is already a compliance check for the layering. So all one would really need is add something similar at the grouping step. The big advantage of having a compliance check at the grouping step is that layers could then be "sub-layered" if needed. If one only merges them at the very end, no chance to look for sub-components. 

Here's some mock data for a case that cannot be solved with a Convex/Fluffy Hull, in case it comes in handy: 
[debug_107_B.csv](https://github.com/MeteoSwiss/ampycloud/files/13270293/debug_107_B.csv)


![ampycloud_demo_B](https://github.com/MeteoSwiss/ampycloud/assets/13974615/b5f155c5-fa71-42b3-a9f9-bcb3530edf0f)

**Comment by regDaniel** [comment]
Ah yes, sure, I'll do it at the grouping step. Somehow my mind was set on doing an overlap check in the grouping such that I forgot that I could also just do a simple compliance step at grouping level with minimal side effects. I'll discuss with @loforest what we do about the hull, clearly it has less priority, but I still like it as it would handle most of the cases I've seen and it handles outliers of a given group properly as long as they are not fully isolated. Thanks for the mock data, very useful! I'll probably add some of the other cases I've found with our ceilo data.
