### ISSUE TITLE
[New Feature]: fix the fluffiness boost parameter to 2 ?

### ISSUE THREAD

**Issue by fpavogt** [MeteoSwiss/ampycloud#123]
### Describe the new feature

Hey @regDaniel, Following our discussion yesterday, I will set the `fluffiness_boost` parameter to 2 in the article. I would propose to also do it in the code, i.e. remove this parameter from the list. 

I would then also argue that we should go all the way and remove the `boost` parameter from the `get_fluffiness()` function in `fluffer.py`, and simple hardcode `2` on l.72. 

Thoughts ?

**Comment by regDaniel** [comment]
I fully support this idea. The choice of the factor 2 is physically well motivated and if we can reduce the size of the parameter space, we should probably do so. Maybe we should ask @loforest if he's ok with the idea.
