### ISSUE TITLE
[Bug]: CITATION file cannot be parsed

### ISSUE THREAD

**Issue by fpavogt** [MeteoSwiss/ampycloud#136]
### Is there already an issue for this?

- [X] I found no existing issue for this bug.

### Describe the bug

The recent PR #135 did not work as expected:

"Your CITATION.cff file cannot be parsed. Make sure the formatting is correct. [Learn more about CITATION files.](https://docs.github.com/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files)"

### Environment

```markdown
- OS:
- Python:
- ampycloud:
```

### Code of Conduct

- [X] I agree to follow the ampycloud Code of Conduct.

**Comment by fpavogt** [comment]
@regDaniel: well .... 😭 

I'll take a look and fix this asap.

**Comment by regDaniel** [comment]
oh no! but not overly urgent from my side of course.

**Comment by fpavogt** [comment]
Solved in #138.
