### ISSUE TITLE
[Bug]: Version conflict between scipy 1.14.1 and statsmodels 0.14.2 

### ISSUE THREAD

**Issue by regDaniel** [MeteoSwiss/ampycloud#139]
### Is there already an issue for this?

- [X] I found no existing issue for this bug.

### Describe the bug

See [this scipy issue](https://github.com/scipy/scipy/issues/21434). For the time being, the workaround is to fix scipy to 1.14.0. We should periodically check if the incompatibility is gone with a newer version of scipy and/ or statsmodels and if that's the case, we can delete the corresponding version fixing in `setup.py`.

### Environment

```markdown
- OS:MacOSX
- Python:3.11
- ampycloud:2.0.0
```

### Code of Conduct

- [X] I agree to follow the ampycloud Code of Conduct.

**Comment by nickodell** [comment]
This issue is fixed in statsmodels==0.14.3, see https://github.com/statsmodels/statsmodels/issues/9333

**Comment by regDaniel** [comment]
very cool, thanks a lot @nickodell for letting us know! I will adapt our dependencies accordingly.
