### ISSUE TITLE
Resampling large gaps should result in NaNs

### ISSUE THREAD

**Issue by fpavogt** [MeteoSwiss/ampycloud#81]
**Describe the change**
When resampling profiles, large gaps should result in NaNs. We absolutely do not want to interpolate over large distances. 

The maximum time gaps should be set to: 2s ?

@GonzagueRomanens, @g-martucci, @cfelix-ch: do you think this number is reasonable ?

**Comment by cfelix-ch** [comment]
@fpavogt go for 2s!

**Comment by fpavogt** [comment]
This issue was opened in the wrong repo.

**Comment by g-martucci** [comment]
@fpavogt<https://github.com/fpavogt> 2-second gap to be linearly interpolated makes sense and is safe. For temperature profiles even 5 seconds could be reasonable as the profile is largely linear, but for humidity 2 seconds should be the maximum size.
