### ISSUE TITLE
`perc` vs `frac` ?

### ISSUE THREAD

**Issue by fpavogt** [MeteoSwiss/ampycloud#94]
**Describe the change**
At the moment, some ampycloud parameters are set in *percentage* (i.e. [0, 100]), whereas others are set in *fractions* (i.e. [0, 1]). Each case is all clearly documented (I think).

But @pjuda's recent review of #86 raises the following question: should all parameters be of one type only ? And if so, which one ?

@loforest, @pjuda, @sibalm: I do not really care either way. It's just some minor tweaks to the code. Do you have a strong preference for one over the other ?

**Comment by pjuda** [comment]
Hi Frédéric, thanks for starting this discussion! As you mentioned, it is not a major point, as long as it is documented. It's also ok to leave it as is. If we were to make it consistent, I would probably opt for fractions. The reason: if I remember correctly, we also use fractions (and not percentages) in autometpy.

**Comment by fpavogt** [comment]
Closing this issue for now - does not appear to be an issue in the end.
